graph LR
    %% Definición de estilos
    classDef frontend fill:#e1f5fe,stroke:#03a9f4,stroke-width:2px;
    classDef gateway fill:#e8eaf6,stroke:#3f51b5,stroke-width:2px;
    classDef service fill:#e3f2fd,stroke:#2196f3,stroke-width:2px;
    classDef storage fill:#fff3e0,stroke:#ff9800,stroke-width:2px;
    classDef queue fill:#fbe9e7,stroke:#ff5722,stroke-width:2px;
    classDef db fill:#e8f5e9,stroke:#4caf50,stroke-width:2px;
    classDef mail fill:#fafafa,stroke:#9e9e9e,stroke-width:2px;

    %% Nodos
    A[Cliente Web<br/>React]:::frontend
    
    B[Api Gateway<br/>.Net 8]:::gateway
    C[Api Auth<br/>Jwt Bearer<br/>.Net 8]:::gateway
    
    D[Microservicio de control<br/>Publicador<br/>.Net 8/9]:::service
    E[Servicio de archivos distribuido<br/>Seaweed FS]:::storage
    
    F[Microservicio de carga masiva<br/>Publicador / Consumidor<br/>.Net 8]:::service
    G((RabbitMQ<br/>Servicio de colas y mensajería)):::queue
    
    H[(Base de datos<br/>SQLServer)]:::db
    
    I[Microservicio de notificación<br/>Consumidor<br/>.Net 8]:::service
    J[MailKit<br/>Envío de correo]:::mail

    %% Conexiones
    A -- Json / Jwt --> B
    B -- Authentication --> C
    C -.-> B
    B -- Jwt --> D
    
    D -- Guarda archivo --> E
    D -- Encola el mensaje --> G
    
    E -- Extrae los archivos a cargar --> F
    G -- Consume los archivos encolados --> F
    
    F -- Persiste información --> H
    F -- Envía la notificación de termino --> G
    
    G -- Consume las notificaciones encoladas --> I
    I -- Actualizar estado --> H
    I --> J